In [1]:
import pandas as pd

## Dataset description

* **Gender**: Gender of the passengers (Female, Male)

* **Customer Type**: The customer type (Loyal customer, disloyal customer)

* **Age**: The actual age of the passengers

* **Type of Travel**: Purpose of the flight of the passengers (Personal Travel, Business Travel)

* **Class**: Travel class in the plane of the passengers (Business, Eco, Eco Plus)

* **Flight distance**: The flight distance of this journey

* **Inflight wifi service**: Satisfaction level of the inflight wifi service (0:Not Applicable;1-5)

* **Departure/Arrival time convenient**: Satisfaction level of Departure/Arrival time convenient

* **Ease of Online booking**: Satisfaction level of online booking

* **Gate location**: Satisfaction level of Gate location

* **Food and drink**: Satisfaction level of Food and drink

* **Online boarding**: Satisfaction level of online boarding

* **Seat comfort**: Satisfaction level of Seat comfort

* **Inflight entertainment**: Satisfaction level of inflight entertainment

* **On-board service**: Satisfaction level of On-board service

* **Leg room service**: Satisfaction level of Leg room service

* **Baggage handling**: Satisfaction level of baggage handling

* **Check-in service**: Satisfaction level of Check-in service

* **Inflight service**: Satisfaction level of inflight service

* **Cleanliness**: Satisfaction level of Cleanliness

* **Departure Delay in Minutes**: Minutes delayed when departure

* **Arrival Delay in Minutes**: Minutes delayed when Arrival

* **Satisfaction**: Airline satisfaction level(Satisfaction, neutral or dissatisfaction)

*Source: kaggle.com*

In [9]:
df = pd.read_csv('train.csv')
print(df.shape)
df.head()

(103904, 24)

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [13]:
test = pd.read_csv('test.csv')
print(test.shape)
test.head()

(25976, 24)

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,3,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,3,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,2,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,4,...,2,2,2,2,4,2,4,0,20.0,satisfied

## Assignment (you can start on Dec, 10)

### Carry out an expolaratory data analysis

1. Check for missing values. If there are any, you should decide what to do with them:

* Usually, if most of the data (>60%) in the column is missing and the column is not crucial for modelling, you can just delete it. 

You can replace the missing data with:
- a measure of the central tendency over the entire column
- a measure of the central tendency within the group
- a random element

**Quantitative data**:
- **Continuous**
  - Symmetric distribution:
    - replace with **median**/mean
  - Asymmetric distribution:
    - replace with median
- **Discrete**
  - replace with mode / average

**Categorical data**:
  - replace with mode
  
Another option is to create a separate model and use it for predicting missing values.

2. Carry out univariate analysis. Use .describe(), vizualization and other methods to check out the distribution of the columns. Are there any outliers? If there are, you can drop them or replace them similarly to missing values. There are also a bunch of other methods to work with outliers, feel free to do more research!

3. Carry out multivariate analysis. For example, you can use scatter plots and a correlation matrix. *Side note: keep in mind that correlation only checks for linear dependencies. If the correlation is small, it doesn't mean that there is no dependency at all, only that there is no **linear** dependency.*

4. Use grouping (.group), filterings (for example, like this ``df[df[col] > df[col].quantile(.95)]``), vizualizations to formulate different hypothesis about the data. For example, maybe loyal customers are usually business travelers? Check it out! Don't forget to write down your conclusions.

The grade for this part will be based on:
1. Completing the plan above (2 points)
2. Cleanliness of your code and formatting of jupyter notebook: It should be filled with comments to your code and conclusions to your research, so we can understand follow your ideas. You should also strive to demonstrate your pandas knowledge and use as much methods from the lecture as possible (3 points)
3. How full your EDA is: imagine that this is a real-life project for your job. Try to test as many interesting and useful to business hypothesis as possible. You will get a higher grade for this criteria if you present a detailed and useful analysis, rather than just checking random correlations. (10 points)

In [ ]:
# your code here :)

## Assignment (you can start on Dec, 11)

1. Create new features based on your EDA. Don't forget to check how they performed after you are finished with modelling! You can use ``feature_importances`` from scikit-learn or use advanced methods like SHAP or Lime. (5 points)
2. Your target variable is ``satisfaction``. You should research metrics and choose one or multiple that you will use to validate your model. Write down the formula(s) and your motivation to use them. (3 points)
2. Design the validation process: for example, will you use cross-validation or just train-test split? Will you account for the imbalance in classes, if it exists? (2 points)
3. Experiment with modelling. You can use models from the lecture or do your own research. You can also try out approaches like stacking and blending â€“ will they increase the quality? (15 points)
4. Make predictions on the test.csv dataset.

In [ ]:
# your code here :)